set a=˜^‰æ‚ðI—¹‚µ‚Ü‚µ‚½
set b=01:25`01:40“úƒeƒŒ‚P
set c=‰Élƒ‰ƒaƒI`‚ˆ‚‰|‚h‚l‚`‚f‚h‚m‚d@‚q‚`‚c‚h‚n`
set d=@5MYUI
chcp 65001
echo %a%>C:\TV\EDCB\twitterbot\tweet.txt
echo %b%>>C:\TV\EDCB\twitterbot\tweet.txt
echo %c%>>C:\TV\EDCB\twitterbot\tweet.txt
echo %d%>>C:\TV\EDCB\twitterbot\tweet.txt
php C:\TV\EDCB\twitterbot\tweet.php