set a=˜^‰æ‚ð’Ç‰Á‚µ‚Ü‚µ‚½
set b=02:04`02:34“úƒeƒŒ‚P
set c=’†ŠÔŠÇ—˜^ƒgƒlƒKƒ@Agenda14@‚`‚Ž‚‰‚ƒ‚ˆ‚t
set d=@5MYUI
chcp 65001
echo %a%>C:\TV\EDCB\twitterbot\tweet.txt
echo %b%>>C:\TV\EDCB\twitterbot\tweet.txt
echo %c%>>C:\TV\EDCB\twitterbot\tweet.txt
echo %d%>>C:\TV\EDCB\twitterbot\tweet.txt
php C:\TV\EDCB\twitterbot\tweet.php
