set a=˜^‰æ‚ðI—¹‚µ‚Ü‚µ‚½
set b=01:05`01:35‚s‚n‚j‚x‚n@‚l‚w‚P
set c=‚q‚d‚’‚‰‚„‚…‚c|‰z‚¦‚ÌƒfƒŠƒ_|@”‚Uu’T‚éŽÒA‰B‚·ŽÒv
set d=@5MYUI
chcp 65001
echo %a%>C:\TV\EDCB\twitterbot\tweet.txt
echo %b%>>C:\TV\EDCB\twitterbot\tweet.txt
echo %c%>>C:\TV\EDCB\twitterbot\tweet.txt
echo %d%>>C:\TV\EDCB\twitterbot\tweet.txt
php C:\TV\EDCB\twitterbot\tweet.php