set a=˜^‰æ‚ð’Ç‰Á‚µ‚Ü‚µ‚½
set b=$STHH$:$STMM$`$ETHH$:$ETMM$$ServiceName$
set c=$Title$
set d=@5MYUI
chcp 65001
echo %a%>C:\TV\EDCB\twitterbot\tweet.txt
echo %b%>>C:\TV\EDCB\twitterbot\tweet.txt
echo %c%>>C:\TV\EDCB\twitterbot\tweet.txt
echo %d%>>C:\TV\EDCB\twitterbot\tweet.txt
php C:\TV\EDCB\twitterbot\tweet.php
